version: "3"

services:

  bootnode:
    image: atletanetwork/atleta-node:testnet-latest
    container_name: sportchain-bootnode
    volumes:
      - ./chain-data/bootnode:/chain-data
      - ./chainspec.json:/chainspec.json
      - ./bootnode-entrypoint.sh:/entrypoint.sh
    env_file:
      - ./node-keys.env
    entrypoint: ["/entrypoint.sh"]
    environment:
      - NODE_KEY=66d0f50a1293fb0e042b409ae0715b8e82bb6d01528e164c6694fa6fc876d585
      - RESERVED_NODES=${RESERVED_NODES}
    ports:
      - "0.0.0.0:30333:30333"
    networks:
      sportchain-node-network:
        ipv4_address: 172.16.238.10

  diego:
    image: atletanetwork/atleta-node:testnet-latest
    container_name: sportchain-diego
    restart: always
    volumes:
      - ./chain-data/diego:/chain-data
      - ./chainspec.json:/chainspec.json
    env_file:
      - node-keys.env
    command: >
      --chain /chainspec.json
      --base-path /chain-data
      --force-authoring
      --rpc-port 9944
      --rpc-cors all
      --unsafe-rpc-external
      --rpc-methods=Unsafe
      --validator
      --name "DIEGO"
      --state-pruning archive
      --allow-private-ipv4
      --node-key "$DIEGO_NODE_KEY_PRIV"
      --port 30444
      --bootnodes /ip4/172.16.238.10/tcp/30333/p2p/12D3KooWHqMEWZUKja1mj2P5o7nkXSrQg7MS5vtcTgmfsp6o4bvp
    ports:
      - "127.0.0.1:9955:9944"
    networks:
      - sportchain-node-network

  pele:
    image: atletanetwork/atleta-node:testnet-latest
    container_name: sportchain-pele
    restart: always
    volumes:
      - ./chain-data/pele:/chain-data
      - ./chainspec.json:/chainspec.json
    env_file:
      - node-keys.env
    command: >
      --chain /chainspec.json
      --base-path /chain-data
      --force-authoring
      --rpc-port 9944
      --rpc-cors all
      --unsafe-rpc-external
      --rpc-methods=Unsafe
      --validator
      --name "PELE"
      --state-pruning archive
      --allow-private-ipv4
      --node-key "$PELE_NODE_KEY_PRIV"
      --port 30555
      --bootnodes /ip4/172.16.238.10/tcp/30333/p2p/12D3KooWHqMEWZUKja1mj2P5o7nkXSrQg7MS5vtcTgmfsp6o4bvp
    ports:
      - "127.0.0.1:9966:9944"
    networks:
      - sportchain-node-network

  franz:
    image: atletanetwork/atleta-node:testnet-latest
    container_name: sportchain-franz
    restart: always
    volumes:
      - ./chain-data/franz:/chain-data
      - ./chainspec.json:/chainspec.json
    env_file:
      - node-keys.env
    command: >
      --chain /chainspec.json
      --base-path /chain-data
      --force-authoring
      --rpc-port 9944
      --rpc-cors all
      --unsafe-rpc-external
      --rpc-methods=Unsafe
      --validator
      --name "FRANZ"
      --state-pruning archive
      --allow-private-ipv4
      --node-key "$FRANZ_NODE_KEY_PRIV"
      --port 30666
      --bootnodes /ip4/172.16.238.10/tcp/30333/p2p/12D3KooWHqMEWZUKja1mj2P5o7nkXSrQg7MS5vtcTgmfsp6o4bvp
    ports:
      - "127.0.0.1:9977:9944"
    networks:
      - sportchain-node-network

networks:
  sportchain-node-network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.16.238.0/24
