version: "3"

services:
  telemetry-frontend:
    image: parity/substrate-telemetry-frontend
    container_name: telemetry-frontend
    env_file:
      - ./docker_conf.env
    read_only: true
    tmpfs:
      - /var/cache/nginx:uid=101,gid=101
      - /var/run:uid=101,gid=101
      - /app/tmp:uid=101,gid=101
    environment:
      SUBSTRATE_TELEMETRY_URL: ws://${TELEMETRY_HOST}:8000/feed
    ports:
      - 80:8000
    restart: unless-stopped
    networks:
      - telemetry-network

  telemetry-backend-shard:
    image: parity/substrate-telemetry-backend
    container_name: telemetry-backend-shard
    read_only: true
    command: [
      'telemetry_shard',
      '--listen', '0.0.0.0:8001',
      '--core', 'http://telemetry-backend-core:8000/shard_submit'
      ]
    ports:
      - 8001:8001
    restart: unless-stopped
    networks:
      - telemetry-network

  telemetry-backend-core:
    image: parity/substrate-telemetry-backend
    container_name: telemetry-backend-core
    read_only: true
    command: [
      'telemetry_core',
      '--listen', '0.0.0.0:8000'
      ]
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      - telemetry-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/promconfig:/etc/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - telemetry-network

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager:/alertmanager/data
      - ./alertmanager/config:/etc/alertmanager/
    expose:
      - "9093"
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    restart: unless-stopped
    networks:
      - telemetry-network

  grafana:
    image: grafana/grafana:11.1.1
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-treemap-panel
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - telemetry-network

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/config/loki-config.yml
    volumes:
      - ./loki/loki-config.yml:/etc/config/loki-config.yml
    networks:
      - telemetry-network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail/promtail-config.yml:/etc/config/promtail-config.yml
      - /var/log:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/config/promtail-config.yml
    networks:
      - telemetry-network

networks:
  telemetry-network:
    name: telemetry

volumes:
  grafana-data: