{
 "title": "Substrate Dashboard (stagenet)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "network", "label": "Chain Network", "query": { "query": "label_values(chain)" } },
   {
    "name": "job",
    "label": "Exporter Job",
    "query": {
     "query": "label_values(node_uname_info{chain=\"$network\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "Chain Instance Host",
    "query": {
     "query": "label_values(substrate_build_info{job=\"$job\"},host)"
    }
   },
   {
    "name": "node",
    "label": "Server Host",
    "query": {
     "query": "label_values(node_uname_info{host=\"$instance\"},host)"
    }
   },
   { "name": "diskdevices", "query": "[a-z]+|nvme[0-9]+n[0-9]+" }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "All Alerts Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", host=\"$node\", job=\"$job\"}[$__rate_interval])) by (instance))\n"
    }
   ]
  },
  {
   "title": "Sys Load",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{host=\"$node\",job=\"$job\"}) * 100 / count(count(rate(node_cpu_seconds_total{host=\"$node\",job=\"$job\"}[$__rate_interval])) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{host=\"$node\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{host=\"$node\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{host=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{host=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{host=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{host=\"$node\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{host=\"$node\",job=\"$job\"} )) * 100"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{host=\"$node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{host=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{host=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{host=\"$node\",job=\"$job\"} - node_boot_time_seconds{host=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{host=\"$node\",job=\"$job\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{host=\"$node\",job=\"$job\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{host=\"$node\",job=\"$job\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Network Traffic by Packets",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 14, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{host=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{host=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Schedule timeslices executed by each cpu",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 10, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_schedstat_timeslices_total{host=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "CPU {{ cpu }}"
    }
   ]
  },
  {
   "title": "I/O Usage Times",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{host=\"$node\",job=\"$job\",device=~\"$diskdevices\"} [5m])",
     "legendFormat": "{{device}} - Time spent doing I/Os"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{host=~\"$node\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{host=~\"$node\"} - node_memory_MemAvailable_bytes{host=~\"$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{host=~\"$node\"}",
     "legendFormat": "Avaliable"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{host=~\"$node\"} / (node_memory_MemTotal_bytes{host=~\"$node\"})))* 100",
     "legendFormat": "Used%"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{host=\"$node\",job=\"$job\",mountpoint=\"/\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_filesystem_size_bytes{host=\"$node\",job=\"$job\",mountpoint=\"/\"} - node_filesystem_avail_bytes{host=\"$node\",job=\"$job\",mountpoint=\"/\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_filesystem_avail_bytes{host=\"$node\",job=\"$job\",mountpoint=\"/\"}",
     "legendFormat": "Avaliable"
    },
    {
     "expr": "(1 - (node_filesystem_avail_bytes{host=\"$node\",job=\"$job\",mountpoint=\"/\"} / (node_filesystem_size_bytes{host=\"$node\",job=\"$job\",mountpoint=\"/\"})))* 100",
     "legendFormat": "Used%"
    }
   ]
  },
  {
   "title": "Chain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Height of the chain",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{host=\"[[instance]]\",chain=\"[[network]]\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Block Finalized",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "substrate_block_height{host=\"[[instance]]\",chain=\"[[network]]\",status=~\"finalized|sync_target\"}",
     "legendFormat": "{{instance}} {{status}}"
    }
   ]
  },
  {
   "title": "Networking bytes per second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_network_bytes_total{host=\"[[instance]]\",chain=\"[[network]]\"}[5m])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Block rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(substrate_block_height{status=\"finalized\",host=\"[[instance]]\",chain=\"[[network]]\"}[10m])*60",
     "legendFormat": "{{instance}}  Blocks / minute"
    }
   ]
  },
  {
   "title": "Peers count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count{host=\"[[instance]]\",chain=\"[[network]]\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "sub_libp2p",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_connections{host=\"[[instance]]\",chain=\"[[network]]\"}",
     "legendFormat": "{{instance}} connections"
    },
    {
     "expr": "substrate_sub_libp2p_is_major_syncing{host=\"[[instance]]\",chain=\"[[network]]\"}",
     "legendFormat": "{{instance}} syncing"
    },
    {
     "expr": "substrate_sub_libp2p_kbuckets_num_nodes{host=\"[[instance]]\",chain=\"[[network]]\"}",
     "legendFormat": "{{instance}} num_nodes"
    }
   ]
  },
  {
   "title": "State Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "substrate_state_cache_bytes{host=\"[[instance]]\",chain=\"[[network]]\"}"
    }
   ]
  },
  {
   "title": "Blocks Av per min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(substrate_block_height{host=\"[[instance]]\",chain=\"[[network]]\",status=~\"finalized|best\"}[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Relative Block Production Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(substrate_block_height{status=\"finalized\",host=\"[[instance]]\",chain=\"[[network]]\"}[10m])/rate(substrate_block_height{status=\"finalized\",host=\"[[instance]]\",chain=\"[[network]]\"}[1m])",
     "legendFormat": "rate[10m] / rate[1m]"
    }
   ]
  },
  {
   "title": "GRANDPA Validator Messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(substrate_finality_grandpa_communication_gossip_validator_messages{host=\"[[instance]]\",chain=\"[[network]]\"}[5m])",
     "legendFormat": "{{message}}"
    }
   ]
  },
  {
   "title": "Sync justifications",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "substrate_sync_extra_justifications{host=\"[[instance]]\",chain=\"[[network]]\"}",
     "legendFormat": "{{instance}} active"
    },
    {
     "expr": "substrate_sync_extra_justifications_failed{host=\"[[instance]]\",chain=\"[[network]]\"}",
     "legendFormat": "{{instance}} failed"
    },
    {
     "expr": "substrate_sync_extra_justifications_importing{instance=\"[[instance]]\",network=\"[[network]]\"}",
     "legendFormat": "{{instance}} importing"
    },
    {
     "expr": "substrate_sync_extra_justifications_pending{instance=\"[[instance]]\",network=\"[[network]]\"}",
     "legendFormat": "{{instance}} pending"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(substrate_tasks_polling_started_total{host=\"[[instance]]\",chain=\"[[network]]\"}[1m]) - rate(substrate_tasks_polling_duration_count{host=\"[[instance]]\",chain=\"[[network]]\"}[1m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Diff -> ( Best Block - Finalized )",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "scalar(substrate_block_height{status=\"best\",host=\"[[instance]]\",chain=\"[[network]]\"})-scalar(substrate_block_height{status=\"finalized\",host=\"[[instance]]\",chain=\"[[network]]\"})",
     "legendFormat": "[[hostname]]"
    }
   ]
  },
  {
   "title": "Queued Blocks (sync)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "substrate_sync_queued_blocks{host=\"[[instance]]\",chain=\"[[network]]\"}"
    }
   ]
  },
  {
   "title": "Active P2P connections per 1 minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_connections_opened_total{host=\"[[instance]]\",chain=\"[[network]]\"}[1m])",
     "legendFormat": "{{instance}}",
     "target": "txcount",
     "type": "timeseries"
    }
   ]
  },
  {
   "title": "TXs Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "substrate_ready_transactions_number{host=\"[[instance]]\",chain=\"[[network]]\"}",
     "legendFormat": "{{instance}}",
     "target": "txcount",
     "type": "timeseries"
    }
   ]
  }
 ]
}