name: Deploy Devnet

on:
  workflow_run:
    workflows: ["Lint shell scripts"]
    types:
      - completed

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: "recursive"

    - name: Install system deps
      run: sudo apt-get install jq 
 
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        touch ~/.ssh/known_hosts
        ssh-keyscan ${{ secrets.DEVNET_HOST }} >> ~/.ssh/known_hosts
        echo "${{ secrets.DEVNET_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent)

    - name: Authenticate GitHub CLI and download latest release of chainspec
      run: |
        gh auth login --with-token <<< "${{ secrets.ACCESS_TOKEN }}"
        LATEST_RELEASE=$(gh release list --repo ${{ secrets.ATLETA_REPO }} --json tagName,createdAt --jq '.[] | select(.tagName | startswith("devnet")) | .tagName' | sort -r | head -n 1)
        echo "${LATEST_RELEASE}"
        gh release download "${LATEST_RELEASE}" --repo ${{ secrets.ATLETA_REPO }} --pattern "chain-spec.devnet.json" --dir chainspecs

    - name: Copy Files to Server
      run: |
        scp devnet/docker-compose.yml ${{ secrets.DEVNET_USERNAME }}@${{ secrets.DEVNET_HOST }}:/sportchain/docker-compose.yml
        scp chainspecs/chain-spec.devnet.json ${{ secrets.DEVNET_USERNAME }}@${{ secrets.DEVNET_HOST }}:/sportchain/chainspec.json
        
    - name: SSH into Server and Deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEVNET_HOST }}
        username: ${{ secrets.DEVNET_USERNAME }}
        key: ${{ secrets.DEVNET_PRIVATE_KEY }}
        script: |
          cd /sportchain
          docker compose down
          docker compose pull
          docker compose up -d --build --remove-orphans
