name: Deploy Telemetry for Devnet

on:
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install system deps
      run: sudo apt-get install gettext

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        touch ~/.ssh/known_hosts
        ssh-keyscan ${{ secrets.DEVNET_HOST }} >> ~/.ssh/known_hosts
        echo "${{ secrets.DEVNET_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent)

    - name: Substitute environment variables
      env:
        DEVNET_HOST: ${{ secrets.DEVNET_HOST }}
      run: |
        envsubst < utils/telemetry/prometheus/prometheus.yml > utils/telemetry/prometheus/prometheus.fill.yml

    - name: Generate config.env
      run: |
        touch utils/telemetry/docker_conf.env
        echo "DEVNET_HOST=${{ secrets.DEVNET_HOST }}" >> utils/telemetry/docker_conf.env

    - name: Copy Files to Server
      run: |
        scp utils/telemetry/docker-compose.yml ${{ secrets.DEVNET_USERNAME }}@${{ secrets.DEVNET_HOST }}:/sportchain/telemetry/docker-compose.yml
        scp utils/telemetry/docker_conf.env ${{ secrets.DEVNET_USERNAME }}@${{ secrets.DEVNET_HOST }}:/sportchain/telemetry/docker_conf.env
        scp utils/telemetry/prometheus/prometheus.fill.yml ${{ secrets.DEVNET_USERNAME }}@${{ secrets.DEVNET_HOST }}:/sportchain/telemetry/prometheus/prometheus.yml
        
    - name: SSH into Server and Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DEVNET_HOST }}
        username: ${{ secrets.DEVNET_USERNAME }}
        key: ${{ secrets.DEVNET_PRIVATE_KEY }}
        script: |
          cd /sportchain/telemetry
          docker compose down
          docker compose pull
          docker compose up --detach --build --remove-orphans
