name: Lint shell scripts

on:
    push:
      branches:
        - '**'
    pull_request:
      branches:
        - '**' 

jobs:
  shellcheck:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: "recursive"

    - name: Install system deps on Linux
      if: ${{ runner.os == 'Linux' }}
      run: sudo apt-get install shellcheck fd-find
    
    - name: Install system deps on MacOS  
      if: ${{ runner.os == 'MacOS' }}
      run: brew install shellcheck fd


    - name: Run shellcheck on Linux
      if: ${{ runner.os == 'Linux' }}
      run: fdfind --type executable --exec shellcheck {}

    - name: Run shellcheck on MacOS
      if: ${{ runner.os == 'MacOS' }}
      run: fd --type executable --exec shellcheck {}
