name: Lint shell scripts

on:
    push:
      branches:
        - '**'
    pull_request:
      branches:
        - '**' 

jobs:
  shellcheck:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: "recursive"

    - name: Install system deps
      run: sudo apt-get install shellcheck fd-find
    
    - name: Run shellcheck 
      run: fdfind --type executable --exec bash -c 'echo {}; shellcheck {}'
