name: Revert Stagenet

on:
  workflow_dispatch:

jobs:

  stop_public_bootnode:

    runs-on: ubuntu-latest
    environment: mainnet

    needs: 
      - stop_validators
      - stop_arch_nodes

    steps:
    - uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        touch ~/.ssh/known_hosts
        ssh-keyscan ${{ secrets.BOOT_NODE_1_HOST }} >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent)

    - name: SSH into Server and Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.BOOT_NODE_1_HOST }}
        username: ${{ secrets.BOOT_NODE_1_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker stop bootnode
          docker rm bootnode

  stop_validators:

    runs-on: ubuntu-latest
    environment: mainnet

    strategy:
      matrix:
        include:

          - node_index: 1
            host_key: VALIDATOR_1_HOST
            user_key: VALIDATOR_1_USER
            priv_node_key: VALIDATOR_1_NODE_KEY_PRIV

          - node_index: 2
            host_key: VALIDATOR_2_HOST
            user_key: VALIDATOR_2_USER
            priv_node_key: VALIDATOR_2_NODE_KEY_PRIV

          - node_index: 3
            host_key: VALIDATOR_3_HOST
            user_key: VALIDATOR_3_USER
            priv_node_key: VALIDATOR_3_NODE_KEY_PRIV

          - node_index: 4
            host_key: VALIDATOR_4_HOST
            user_key: VALIDATOR_4_USER
            priv_node_key: VALIDATOR_4_NODE_KEY_PRIV

          - node_index: 5
            host_key: VALIDATOR_5_HOST
            user_key: VALIDATOR_5_USER
            priv_node_key: VALIDATOR_5_NODE_KEY_PRIV

          - node_index: 6
            host_key: VALIDATOR_6_HOST
            user_key: VALIDATOR_6_USER
            priv_node_key: VALIDATOR_6_NODE_KEY_PRIV

          - node_index: 7
            host_key: VALIDATOR_7_HOST
            user_key: VALIDATOR_7_USER
            priv_node_key: VALIDATOR_7_NODE_KEY_PRIV
            
          - node_index: 8
            host_key: VALIDATOR_8_HOST
            user_key: VALIDATOR_8_USER
            priv_node_key: VALIDATOR_8_NODE_KEY_PRIV

          - node_index: 9
            host_key: VALIDATOR_9_HOST
            user_key: VALIDATOR_9_USER
            priv_node_key: VALIDATOR_9_NODE_KEY_PRIV

          - node_index: 10
            host_key: VALIDATOR_10_HOST
            user_key: VALIDATOR_10_USER
            priv_node_key: VALIDATOR_10_NODE_KEY_PRIV

          - node_index: 11
            host_key: VALIDATOR_11_HOST
            user_key: VALIDATOR_11_USER
            priv_node_key: VALIDATOR_11_NODE_KEY_PRIV

          - node_index: 12
            host_key: VALIDATOR_12_HOST
            user_key: VALIDATOR_12_USER
            priv_node_key: VALIDATOR_12_NODE_KEY_PRIV

          - node_index: 13
            host_key: VALIDATOR_13_HOST
            user_key: VALIDATOR_13_USER
            priv_node_key: VALIDATOR_13_NODE_KEY_PRIV

          - node_index: 14
            host_key: VALIDATOR_14_HOST
            user_key: VALIDATOR_14_USER
            priv_node_key: VALIDATOR_14_NODE_KEY_PRIV

          - node_index: 15
            host_key: VALIDATOR_15_HOST
            user_key: VALIDATOR_15_USER
            priv_node_key: VALIDATOR_15_NODE_KEY_PRIV

    steps:
    - uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        touch ~/.ssh/known_hosts
        ssh-keyscan ${{ secrets[matrix.host_key] }} >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent)

    - name: SSH into Server and Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets[matrix.host_key] }}
        username: ${{ secrets[matrix.user_key] }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker stop validator_mainnet
          docker rm validator_mainnet

  stop_arch_nodes:

    runs-on: ubuntu-latest
    environment: mainnet

    strategy:
      matrix:
        include:

          - node_index: 1
            host_key: ARCH_1_HOST
            user_key: ARCH_1_USER
            priv_node_key: ARCH_1_NODE_KEY_PRIV

          - node_index: 2
            host_key: ARCH_2_HOST
            user_key: ARCH_2_USER
            priv_node_key: ARCH_2_NODE_KEY_PRIV

          - node_index: 3
            host_key: ARCH_3_HOST
            user_key: ARCH_3_USER
            priv_node_key: ARCH_3_NODE_KEY_PRIV

          - node_index: 4
            host_key: ARCH_4_HOST
            user_key: ARCH_4_USER
            priv_node_key: ARCH_4_NODE_KEY_PRIV

          - node_index: 5
            host_key: ARCH_5_HOST
            user_key: ARCH_5_USER
            priv_node_key: ARCH_5_NODE_KEY_PRIV

          - node_index: 6
            host_key: ARCH_6_HOST
            user_key: ARCH_6_USER
            priv_node_key: ARCH_6_NODE_KEY_PRIV

          - node_index: 7
            host_key: ARCH_7_HOST
            user_key: ARCH_7_USER
            priv_node_key: ARCH_7_NODE_KEY_PRIV

          - node_index: 8
            host_key: ARCH_8_HOST
            user_key: ARCH_8_USER
            priv_node_key: ARCH_8_NODE_KEY_PRIV

          - node_index: 9
            host_key: ARCH_9_HOST
            user_key: ARCH_9_USER
            priv_node_key: ARCH_9_NODE_KEY_PRIV

          - node_index: 10
            host_key: ARCH_10_HOST
            user_key: ARCH_10_USER
            priv_node_key: ARCH_10_NODE_KEY_PRIV

          - node_index: 11
            host_key: ARCH_11_HOST
            user_key: ARCH_11_USER
            priv_node_key: ARCH_11_NODE_KEY_PRIV

          - node_index: 12
            host_key: ARCH_12_HOST
            user_key: ARCH_12_USER
            priv_node_key: ARCH_12_NODE_KEY_PRIV
        
    steps:
    - uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        touch ~/.ssh/known_hosts
        ssh-keyscan ${{ secrets[matrix.host_key] }} >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent)

    - name: SSH into Server and Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets[matrix.host_key] }}
        username: ${{ secrets[matrix.user_key] }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker stop arch_mainnet
          docker rm arch_mainnet


  revert_public_bootnode:

    environment: mainnet

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install system deps
      run: sudo apt-get install jq wget
    
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        touch ~/.ssh/known_hosts
        ssh-keyscan ${{ secrets.BOOT_NODE_1_HOST }} >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent)

    # - name: Authenticate GitHub CLI and download latest release of chainspec
    #   run: |
    #     gh auth login --with-token <<< "${{ secrets.ACCESS_TOKEN }}"
    #     LATEST_RELEASE=$(gh release list --repo Atleta-network/atleta --json tagName,createdAt --jq '.[] | select(.tagName | startswith("testnet-chainspec")) | .tagName' | sort -r | head -n 1)
    #     echo "${LATEST_RELEASE}"
    #     gh release download "${LATEST_RELEASE}" --repo Atleta-network/atleta --pattern "chain-spec.testnet.json" --dir chainspecs

    - name: Download chainspec
      run: |
        wget https://raw.githubusercontent.com/Atleta-network/atleta/refs/heads/mainnet/chainspecs/chain-spec.mainnet.json

    - name: Prepare variables
      run: |
        echo "BOOT_NODE_KEY_PRIV=${{ secrets.BOOT_NODE_KEY_PRIV }}" >> mainnet/revert/bootnode-keys.env
        echo "BOOT_NODE_KEY_PUB=${{ secrets.BOOT_NODE_KEY_PUB }}" >> mainnet/revert/bootnode-keys.env
        echo "BOOT_NODE_P2P_ADDRESS=${{ secrets.BOOT_NODE_P2P_ADDRESS }}" >> mainnet/revert/bootnode-keys.env
        echo "TELEMETRY_DOMAIN=${{ secrets.TELEMETRY_DOMAIN }}" >> mainnet/revert/bootnode.env
        echo "container_atleta=bootnode" >> mainnet/revert/bootnode.env
        
    - name: Copy files to the server
      run: |
        scp mainnet/update/update-bootnode.sh ${{ secrets.BOOT_NODE_1_USER }}@${{ secrets.BOOT_NODE_1_HOST }}:/sportchain/atleta/update-bootnode.sh
        scp chain-spec.mainnet.json ${{ secrets.BOOT_NODE_1_USER }}@${{ secrets.BOOT_NODE_1_HOST }}:/sportchain/atleta/chainspec.json
        scp mainnet/revert/bootnode-keys.env ${{ secrets.BOOT_NODE_1_USER }}@${{ secrets.BOOT_NODE_1_HOST }}:/sportchain/atleta/bootnode-keys.env
        scp mainnet/revert/bootnode.env ${{ secrets.BOOT_NODE_1_USER }}@${{ secrets.BOOT_NODE_1_HOST }}:/sportchain/atleta/.env
        scp mainnet/revert/revert.sh ${{ secrets.BOOT_NODE_1_USER }}@${{ secrets.BOOT_NODE_1_HOST }}:/sportchain/atleta/revert.sh

    - name: Run bootnode
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.BOOT_NODE_1_HOST }}
        username: ${{ secrets.BOOT_NODE_1_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /sportchain/atleta
          ./revert.sh

  revert_validators:

    runs-on: ubuntu-latest
    environment: mainnet

    needs: 
      - revert_public_bootnode

    strategy:
      matrix:
        include:

        - node_index: 1
          host_key: VALIDATOR_1_HOST
          user_key: VALIDATOR_1_USER
          priv_node_key: VALIDATOR_1_NODE_KEY_PRIV

        - node_index: 2
          host_key: VALIDATOR_2_HOST
          user_key: VALIDATOR_2_USER
          priv_node_key: VALIDATOR_2_NODE_KEY_PRIV

        - node_index: 3
          host_key: VALIDATOR_3_HOST
          user_key: VALIDATOR_3_USER
          priv_node_key: VALIDATOR_3_NODE_KEY_PRIV

        - node_index: 4
          host_key: VALIDATOR_4_HOST
          user_key: VALIDATOR_4_USER
          priv_node_key: VALIDATOR_4_NODE_KEY_PRIV

        - node_index: 5
          host_key: VALIDATOR_5_HOST
          user_key: VALIDATOR_5_USER
          priv_node_key: VALIDATOR_5_NODE_KEY_PRIV

        - node_index: 6
          host_key: VALIDATOR_6_HOST
          user_key: VALIDATOR_6_USER
          priv_node_key: VALIDATOR_6_NODE_KEY_PRIV

        - node_index: 7
          host_key: VALIDATOR_7_HOST
          user_key: VALIDATOR_7_USER
          priv_node_key: VALIDATOR_7_NODE_KEY_PRIV
          
        - node_index: 8
          host_key: VALIDATOR_8_HOST
          user_key: VALIDATOR_8_USER
          priv_node_key: VALIDATOR_8_NODE_KEY_PRIV

        - node_index: 9
          host_key: VALIDATOR_9_HOST
          user_key: VALIDATOR_9_USER
          priv_node_key: VALIDATOR_9_NODE_KEY_PRIV

        - node_index: 10
          host_key: VALIDATOR_10_HOST
          user_key: VALIDATOR_10_USER
          priv_node_key: VALIDATOR_10_NODE_KEY_PRIV

        - node_index: 11
          host_key: VALIDATOR_11_HOST
          user_key: VALIDATOR_11_USER
          priv_node_key: VALIDATOR_11_NODE_KEY_PRIV

        - node_index: 12
          host_key: VALIDATOR_12_HOST
          user_key: VALIDATOR_12_USER
          priv_node_key: VALIDATOR_12_NODE_KEY_PRIV

        - node_index: 13
          host_key: VALIDATOR_13_HOST
          user_key: VALIDATOR_13_USER
          priv_node_key: VALIDATOR_13_NODE_KEY_PRIV

        - node_index: 14
          host_key: VALIDATOR_14_HOST
          user_key: VALIDATOR_14_USER
          priv_node_key: VALIDATOR_14_NODE_KEY_PRIV

        - node_index: 15
          host_key: VALIDATOR_15_HOST
          user_key: VALIDATOR_15_USER
          priv_node_key: VALIDATOR_15_NODE_KEY_PRIV

    steps:
    - uses: actions/checkout@v4

    - name: Install system deps
      run: sudo apt-get install jq wget

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        touch ~/.ssh/known_hosts
        ssh-keyscan ${{ secrets[matrix.host_key] }} >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent)

    # - name: Authenticate GitHub CLI and download latest release of chainspec
    #   run: |
    #     gh auth login --with-token <<< "${{ secrets.ACCESS_TOKEN }}"
    #     LATEST_RELEASE=$(gh release list --repo Atleta-network/atleta --json tagName,createdAt --jq '.[] | select(.tagName | startswith("testnet")) | .tagName' | sort -r | head -n 1)
    #     echo "${LATEST_RELEASE}"
    #     gh release download "${LATEST_RELEASE}" --repo Atleta-network/atleta --pattern "chain-spec.testnet.json" --dir chainspecs

    - name: Download chainspec
      run: |
        mkdir chainspecs
        wget -O chainspecs/chain-spec.mainnet.json https://raw.githubusercontent.com/Atleta-network/atleta/refs/heads/mainnet/chainspecs/chain-spec.mainnet.json
      
    - name: Prepare .env files
      run: |
        echo "VALIDATOR_KEY=${{ secrets[matrix.priv_node_key] }}" >> mainnet/revert/validator.env
        echo "BOOT_NODE_P2P_ADDRESS=\"${{ secrets.BOOT_NODE_P2P_ADDRESS }}\"" >> mainnet/revert/validator.env
        echo "INDEX=${{ matrix.node_index }}" >> mainnet/revert/validator.env
        echo "TELEMETRY_DOMAIN=${{ secrets.TELEMETRY_DOMAIN }}" >> mainnet/revert/validator.env
        echo "container_atleta=validator_mainnet" >> mainnet/revert/validator.env

    - name: Copy Files to Server
      run: |
        scp mainnet/update/update-validator.sh ${{ secrets[matrix.user_key] }}@${{ secrets[matrix.host_key] }}:/sportchain/atleta/update-validator.sh
        scp mainnet/revert/mainnet.keys.env ${{ secrets[matrix.user_key] }}@${{ secrets[matrix.host_key] }}:/sportchain/atleta/mainnet.keys.env
        scp chainspecs/chain-spec.mainnet.json ${{ secrets[matrix.user_key] }}@${{ secrets[matrix.host_key] }}:/sportchain/atleta/chainspec.json
        scp mainnet/revert/validator.env ${{ secrets[matrix.user_key] }}@${{ secrets[matrix.host_key] }}:/sportchain/atleta/.env
        scp utils/telemetry/process-exporter/process-exporter.yml ${{ secrets[matrix.user_key] }}@${{ secrets[matrix.host_key] }}:/sportchain/atleta/process-exporter/process-exporter.yml

    - name: SSH into Server and Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets[matrix.host_key] }}
        username: ${{ secrets[matrix.user_key] }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /sportchain/atleta
          ./revert.sh

  revert_arch_nodes:

    runs-on: ubuntu-latest
    environment: mainnet

    needs: 
      - revert_public_bootnode

    strategy:
      matrix:
        include:

          - node_index: 1
            host_key: ARCH_1_HOST
            user_key: ARCH_1_USER
            priv_node_key: ARCH_1_NODE_KEY_PRIV

          - node_index: 2
            host_key: ARCH_2_HOST
            user_key: ARCH_2_USER
            priv_node_key: ARCH_2_NODE_KEY_PRIV

          - node_index: 3
            host_key: ARCH_3_HOST
            user_key: ARCH_3_USER
            priv_node_key: ARCH_3_NODE_KEY_PRIV

          - node_index: 4
            host_key: ARCH_4_HOST
            user_key: ARCH_4_USER
            priv_node_key: ARCH_4_NODE_KEY_PRIV

          - node_index: 5
            host_key: ARCH_5_HOST
            user_key: ARCH_5_USER
            priv_node_key: ARCH_5_NODE_KEY_PRIV

          - node_index: 6
            host_key: ARCH_6_HOST
            user_key: ARCH_6_USER
            priv_node_key: ARCH_6_NODE_KEY_PRIV

          - node_index: 7
            host_key: ARCH_7_HOST
            user_key: ARCH_7_USER
            priv_node_key: ARCH_7_NODE_KEY_PRIV

          - node_index: 8
            host_key: ARCH_8_HOST
            user_key: ARCH_8_USER
            priv_node_key: ARCH_8_NODE_KEY_PRIV

          - node_index: 9
            host_key: ARCH_9_HOST
            user_key: ARCH_9_USER
            priv_node_key: ARCH_9_NODE_KEY_PRIV

          - node_index: 10
            host_key: ARCH_10_HOST
            user_key: ARCH_10_USER
            priv_node_key: ARCH_10_NODE_KEY_PRIV

          - node_index: 11
            host_key: ARCH_11_HOST
            user_key: ARCH_11_USER
            priv_node_key: ARCH_11_NODE_KEY_PRIV

          - node_index: 12
            host_key: ARCH_12_HOST
            user_key: ARCH_12_USER
            priv_node_key: ARCH_12_NODE_KEY_PRIV
        
    steps:
    - uses: actions/checkout@v4

    - name: Install system deps
      run: sudo apt-get install jq wget

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        touch ~/.ssh/known_hosts
        ssh-keyscan ${{ secrets[matrix.host_key] }} >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent)

    # - name: Authenticate GitHub CLI and download latest release of chainspec
    #   run: |
    #     gh auth login --with-token <<< "${{ secrets.ACCESS_TOKEN }}"
    #     LATEST_RELEASE=$(gh release list --repo Atleta-network/atleta --json tagName,createdAt --jq '.[] | select(.tagName | startswith("testnet")) | .tagName' | sort -r | head -n 1)
    #     echo "${LATEST_RELEASE}"
    #     gh release download "${LATEST_RELEASE}" --repo Atleta-network/atleta --pattern "chain-spec.testnet.json" --dir chainspecs

    - name: Download chainspec
      run: |
        mkdir chainspecs
        wget -O chainspecs/chain-spec.mainnet.json https://raw.githubusercontent.com/Atleta-network/atleta/refs/heads/mainnet/chainspecs/chain-spec.mainnet.json

    - name: Prepare .env files
      run: |
        echo "BOOT_NODE_P2P_ADDRESS=\"${{ secrets.BOOT_NODE_P2P_ADDRESS }}\"" >> mainnet/revert/arch-node.env
        echo "INDEX=${{ matrix.node_index }}" >> mainnet/revert/arch-node.env
        echo "TELEMETRY_DOMAIN=${{ secrets.TELEMETRY_DOMAIN }}" >> mainnet/revert/arch-node.env
        echo "container_atleta=arch_mainnet" >> mainnet/revert/arch-node.env

    - name: Copy Files to Server
      run: |
        scp mainnet/deploy/run-arch-node.sh ${{ secrets[matrix.user_key] }}@${{ secrets[matrix.host_key] }}:/sportchain/atleta/run-arch-node.sh
        scp chainspecs/chain-spec.mainnet.json ${{ secrets[matrix.user_key] }}@${{ secrets[matrix.host_key] }}:/sportchain/atleta/chainspec.json
        scp mainnet/revert/arch-node.env ${{ secrets[matrix.user_key] }}@${{ secrets[matrix.host_key] }}:/sportchain/atleta/.env
        scp mainnet/revert/promtail-config.yml ${{ secrets[matrix.user_key] }}@${{ secrets[matrix.host_key] }}:/sportchain/atleta/promtail/promtail-config.yml

    - name: SSH into Server and Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets[matrix.host_key] }}
        username: ${{ secrets[matrix.user_key] }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /sportchain/atleta
          ./revert.sh  
