name: Wipe Mainnet

on:
  workflow_dispatch:

jobs:
  wipe_public_bootnode:

    needs: 
      - wipe_validators
      - wipe_arch_nodes

    environment: mainnet

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
   
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        touch ~/.ssh/known_hosts
        ssh-keyscan ${{ secrets.BOOT_NODE_1_HOST }} >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent)

    - name: Prepare variables
      run: |
        echo "container_atleta=bootnode" >> mainnet/wipe/cleanup.env
        echo "container_process_exporter=process-exporter" >> stagenet/wipe/cleanup.env
        echo "container_promtail=promtail" >> stagenet/wipe/cleanup.env
     
    - name: Copy files to the server
      run: |
        scp mainnet/wipe/cleanup.env ${{ secrets.BOOT_NODE_1_USER }}@${{ secrets.BOOT_NODE_1_HOST }}:/tmp/cleanup.env 
        scp mainnet/wipe/wipe.sh ${{ secrets.BOOT_NODE_1_USER }}@${{ secrets.BOOT_NODE_1_HOST }}:/tmp/wipe.sh

    - name: Wipe bootnode
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.BOOT_NODE_1_HOST }}
        username: ${{ secrets.BOOT_NODE_1_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /tmp
          ./wipe.sh
          rm -f cleanup.env wipe.sh

  wipe_validators:

    runs-on: ubuntu-latest
    environment: mainnet

    strategy:
      matrix:
        include:

          - node_index: 1
            host_key: VALIDATOR_1_HOST
            user_key: VALIDATOR_1_USER
            priv_node_key: VALIDATOR_1_NODE_KEY_PRIV

          - node_index: 2
            host_key: VALIDATOR_2_HOST
            user_key: VALIDATOR_2_USER
            priv_node_key: VALIDATOR_2_NODE_KEY_PRIV

          - node_index: 3
            host_key: VALIDATOR_3_HOST
            user_key: VALIDATOR_3_USER
            priv_node_key: VALIDATOR_3_NODE_KEY_PRIV

          - node_index: 4
            host_key: VALIDATOR_4_HOST
            user_key: VALIDATOR_4_USER
            priv_node_key: VALIDATOR_4_NODE_KEY_PRIV

          - node_index: 5
            host_key: VALIDATOR_5_HOST
            user_key: VALIDATOR_5_USER
            priv_node_key: VALIDATOR_5_NODE_KEY_PRIV

          - node_index: 6
            host_key: VALIDATOR_6_HOST
            user_key: VALIDATOR_6_USER
            priv_node_key: VALIDATOR_6_NODE_KEY_PRIV

          - node_index: 7
            host_key: VALIDATOR_7_HOST
            user_key: VALIDATOR_7_USER
            priv_node_key: VALIDATOR_7_NODE_KEY_PRIV
            
          - node_index: 8
            host_key: VALIDATOR_8_HOST
            user_key: VALIDATOR_8_USER
            priv_node_key: VALIDATOR_8_NODE_KEY_PRIV

          - node_index: 9
            host_key: VALIDATOR_9_HOST
            user_key: VALIDATOR_9_USER
            priv_node_key: VALIDATOR_9_NODE_KEY_PRIV

          - node_index: 10
            host_key: VALIDATOR_10_HOST
            user_key: VALIDATOR_10_USER
            priv_node_key: VALIDATOR_10_NODE_KEY_PRIV

          - node_index: 11
            host_key: VALIDATOR_11_HOST
            user_key: VALIDATOR_11_USER
            priv_node_key: VALIDATOR_11_NODE_KEY_PRIV

          - node_index: 12
            host_key: VALIDATOR_12_HOST
            user_key: VALIDATOR_12_USER
            priv_node_key: VALIDATOR_12_NODE_KEY_PRIV

          - node_index: 13
            host_key: VALIDATOR_13_HOST
            user_key: VALIDATOR_13_USER
            priv_node_key: VALIDATOR_13_NODE_KEY_PRIV

          - node_index: 14
            host_key: VALIDATOR_14_HOST
            user_key: VALIDATOR_14_USER
            priv_node_key: VALIDATOR_14_NODE_KEY_PRIV

          - node_index: 15
            host_key: VALIDATOR_15_HOST
            user_key: VALIDATOR_15_USER
            priv_node_key: VALIDATOR_15_NODE_KEY_PRIV

    steps:
    - uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        touch ~/.ssh/known_hosts
        ssh-keyscan ${{ secrets[matrix.host_key] }} >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent)

    - name: Prepare .env files
      run: |
        echo "container_atleta=validator_mainnet" >> mainnet/wipe/cleanup.env
        echo "container_process_exporter=process-exporter" >> stagenet/wipe/cleanup.env
        echo "container_promtail=promtail" >> stagenet/wipe/cleanup.env


    - name: Copy Files to Server
      run: |
        scp mainnet/wipe/cleanup.env ${{ secrets[matrix.user_key] }}@${{ secrets[matrix.host_key] }}:/tmp/cleanup.env
        scp mainnet/wipe/wipe.sh ${{ secrets[matrix.user_key] }}@${{ secrets[matrix.host_key] }}:/tmp/wipe.sh

    - name: SSH into Server and Wipe
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets[matrix.host_key] }}
        username: ${{ secrets[matrix.user_key] }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /tmp
          ./wipe.sh
          # rm -f cleanup.env wipe.sh

  wipe_arch_nodes:

    runs-on: ubuntu-latest
    environment: mainnet

    strategy:
      matrix:
        include:

          - node_index: 1
            host_key: ARCH_1_HOST
            user_key: ARCH_1_USER
            priv_node_key: ARCH_1_NODE_KEY_PRIV

          - node_index: 2
            host_key: ARCH_2_HOST
            user_key: ARCH_2_USER
            priv_node_key: ARCH_2_NODE_KEY_PRIV

          - node_index: 3
            host_key: ARCH_3_HOST
            user_key: ARCH_3_USER
            priv_node_key: ARCH_3_NODE_KEY_PRIV

          - node_index: 4
            host_key: ARCH_4_HOST
            user_key: ARCH_4_USER
            priv_node_key: ARCH_4_NODE_KEY_PRIV

          - node_index: 5
            host_key: ARCH_5_HOST
            user_key: ARCH_5_USER
            priv_node_key: ARCH_5_NODE_KEY_PRIV

          - node_index: 6
            host_key: ARCH_6_HOST
            user_key: ARCH_6_USER
            priv_node_key: ARCH_6_NODE_KEY_PRIV

          - node_index: 7
            host_key: ARCH_7_HOST
            user_key: ARCH_7_USER
            priv_node_key: ARCH_7_NODE_KEY_PRIV

          - node_index: 8
            host_key: ARCH_8_HOST
            user_key: ARCH_8_USER
            priv_node_key: ARCH_8_NODE_KEY_PRIV

          - node_index: 9
            host_key: ARCH_9_HOST
            user_key: ARCH_9_USER
            priv_node_key: ARCH_9_NODE_KEY_PRIV

          - node_index: 10
            host_key: ARCH_10_HOST
            user_key: ARCH_10_USER
            priv_node_key: ARCH_10_NODE_KEY_PRIV

          - node_index: 11
            host_key: ARCH_11_HOST
            user_key: ARCH_11_USER
            priv_node_key: ARCH_11_NODE_KEY_PRIV

          - node_index: 12
            host_key: ARCH_12_HOST
            user_key: ARCH_12_USER
            priv_node_key: ARCH_12_NODE_KEY_PRIV
        
      max-parallel: 1

    steps:
    - uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        touch ~/.ssh/known_hosts
        ssh-keyscan ${{ secrets[matrix.host_key] }} >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent)

    - name: Prepare .env files
      run: |
        echo "container_atleta=arch_mainnet" >> mainnet/wipe/cleanup.env
        echo "container_process_exporter=process-exporter" >> stagenet/wipe/cleanup.env
        echo "container_promtail=promtail" >> stagenet/wipe/cleanup.env

    - name: Copy Files to Server
      run: |
        scp mainnet/wipe/cleanup.env ${{ secrets[matrix.user_key] }}@${{ secrets[matrix.host_key] }}:/tmp/cleanup.env
        scp mainnet/wipe/wipe.sh ${{ secrets[matrix.user_key] }}@${{ secrets[matrix.host_key] }}:/tmp/wipe.sh

    - name: SSH into Server and Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets[matrix.host_key] }}
        username: ${{ secrets[matrix.user_key] }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /tmp
          ./wipe.sh
          rm -f cleanup.env wipe.sh
